/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as MapRouteImport } from './routes/map'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiSstPointRouteImport } from './routes/api/sst/point'
import { Route as ApiSstGridRouteImport } from './routes/api/sst/grid'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSstPointRoute = ApiSstPointRouteImport.update({
  id: '/api/sst/point',
  path: '/api/sst/point',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSstGridRoute = ApiSstGridRouteImport.update({
  id: '/api/sst/grid',
  path: '/api/sst/grid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/store': typeof StoreRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/sst/grid': typeof ApiSstGridRoute
  '/api/sst/point': typeof ApiSstPointRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/store': typeof StoreRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/sst/grid': typeof ApiSstGridRoute
  '/api/sst/point': typeof ApiSstPointRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/store': typeof StoreRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/sst/grid': typeof ApiSstGridRoute
  '/api/sst/point': typeof ApiSstPointRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/map'
    | '/store'
    | '/api/geocode'
    | '/api/sst/grid'
    | '/api/sst/point'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/map'
    | '/store'
    | '/api/geocode'
    | '/api/sst/grid'
    | '/api/sst/point'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/map'
    | '/store'
    | '/api/geocode'
    | '/api/sst/grid'
    | '/api/sst/point'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MapRoute: typeof MapRoute
  StoreRoute: typeof StoreRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiSstGridRoute: typeof ApiSstGridRoute
  ApiSstPointRoute: typeof ApiSstPointRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sst/point': {
      id: '/api/sst/point'
      path: '/api/sst/point'
      fullPath: '/api/sst/point'
      preLoaderRoute: typeof ApiSstPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sst/grid': {
      id: '/api/sst/grid'
      path: '/api/sst/grid'
      fullPath: '/api/sst/grid'
      preLoaderRoute: typeof ApiSstGridRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MapRoute: MapRoute,
  StoreRoute: StoreRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiSstGridRoute: ApiSstGridRoute,
  ApiSstPointRoute: ApiSstPointRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
