/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiSstPointRouteImport } from './routes/api/sst/point'
import { Route as ApiSstGridRouteImport } from './routes/api/sst/grid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSstPointRoute = ApiSstPointRouteImport.update({
  id: '/api/sst/point',
  path: '/api/sst/point',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSstGridRoute = ApiSstGridRouteImport.update({
  id: '/api/sst/grid',
  path: '/api/sst/grid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/sst/grid': typeof ApiSstGridRoute
  '/api/sst/point': typeof ApiSstPointRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/sst/grid': typeof ApiSstGridRoute
  '/api/sst/point': typeof ApiSstPointRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/sst/grid': typeof ApiSstGridRoute
  '/api/sst/point': typeof ApiSstPointRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/geocode' | '/api/sst/grid' | '/api/sst/point'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/geocode' | '/api/sst/grid' | '/api/sst/point'
  id: '__root__' | '/' | '/api/geocode' | '/api/sst/grid' | '/api/sst/point'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiSstGridRoute: typeof ApiSstGridRoute
  ApiSstPointRoute: typeof ApiSstPointRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sst/point': {
      id: '/api/sst/point'
      path: '/api/sst/point'
      fullPath: '/api/sst/point'
      preLoaderRoute: typeof ApiSstPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sst/grid': {
      id: '/api/sst/grid'
      path: '/api/sst/grid'
      fullPath: '/api/sst/grid'
      preLoaderRoute: typeof ApiSstGridRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiSstGridRoute: ApiSstGridRoute,
  ApiSstPointRoute: ApiSstPointRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
